// <auto-generated />
namespace SystemSmallSoft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SystemInitial5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SystemInitial5));
        
        string IMigrationMetadata.Id
        {
            get { return "202008201833480_SystemInitial5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
